name: BackEnd-CI-CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest   
    steps:
      - name: pull code
        uses: actions/checkout@v2

      - name: php migrate
        run: ls
        shell: bash
        
    
