name: BackEnd-CI-CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-22.04  
    steps:
      - name: pull code
        uses: actions/checkout@v2
        
      - name: list files/directories
        run: ls -lah
        shell: bash
        
      - name: show current working directory
        run: pwd
        shell: bash
                
      - name: php migrate
        run: php artisan migrate
        shell: bash
        
    
